const adminTitles={overview:'Resumen general',courses:'Gestión de cursos',students:'Estudiantes',content:'Contenidos',reports:'Reportes',settings:'Configuración'};
const renderAdminCourses=(query='',status='all')=>{const courses=EcoStore.get('courses',EcoData.courses).filter(course=>course.title.toLowerCase().includes(query.toLowerCase())&&(status==='all'||course.status===status));$('#adminCourseTable').innerHTML=`<div class="data-row header"><span>CURSO</span><span>CATEGORÍA</span><span>ESTADO</span><span>ESTUDIANTES</span><span></span></div>${courses.map(course=>`<div class="data-row"><div class="course-cell"><span class="course-mini-icon">${course.icon}</span><strong>${course.title}</strong></div><span>${course.category}</span><span class="status ${course.status==='Publicado'?'published':'draft'}">${course.status}</span><span>${course.students.toLocaleString('es-CO')}</span><span class="row-actions"><button data-delete="${course.id}" title="Eliminar">⋮</button></span></div>`).join('')}`;$$('[data-delete]').forEach(button=>button.addEventListener('click',()=>showToast('Menú de edición disponible para este curso')))};
const openCourseModal=()=>$('#courseModal').classList.add('open');
document.addEventListener('DOMContentLoaded',()=>{
  renderAdminCourses();$('#courseCount').textContent=EcoStore.get('courses',EcoData.courses).length;
  $$('[data-admin-view]').forEach(button=>button.addEventListener('click',()=>{$$('[data-admin-view]').forEach(item=>item.classList.remove('active'));button.classList.add('active');$$('.admin-view').forEach(view=>view.classList.remove('active'));$(`#view-${button.dataset.adminView}`).classList.add('active');$('#adminViewTitle').textContent=adminTitles[button.dataset.adminView];$('.sidebar').classList.remove('open')}));
  $('#newCourseButton').addEventListener('click',openCourseModal);$$('.open-course-modal').forEach(button=>button.addEventListener('click',openCourseModal));
  $('#courseForm').addEventListener('submit',event=>{event.preventDefault();const courses=EcoStore.get('courses',EcoData.courses);const category=$('#newCourseCategory').value;const themes={Clima:'cover-climate',Agua:'cover-water',Circularidad:'cover-circular',Biodiversidad:'cover-climate'};const icons={Clima:'🌤️',Agua:'💧',Circularidad:'♻',Biodiversidad:'🦋'};courses.push({id:`course-${Date.now()}`,title:$('#newCourseTitle').value,category,description:$('#newCourseDescription').value,modules:Number($('#newCourseModules').value),lessons:Number($('#newCourseModules').value)*3,progress:0,rating:0,students:0,icon:icons[category],theme:themes[category],status:$('#newCourseStatus').value});EcoStore.set('courses',courses);renderAdminCourses();$('#courseCount').textContent=courses.length;$('#courseModal').classList.remove('open');event.target.reset();showToast('Curso creado correctamente')});
  $('#adminCourseSearch').addEventListener('input',event=>renderAdminCourses(event.target.value,$('#statusFilter').value));$('#statusFilter').addEventListener('change',event=>renderAdminCourses($('#adminCourseSearch').value,event.target.value));
  $('#exportReport').addEventListener('click',()=>{const content='EcoAula - Informe septiembre 2026\nEstudiantes activos: 12.482\nFinalización: 92.6%\nCursos: 38\nSatisfacción: 4.9/5';const blob=new Blob([content],{type:'text/plain'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='informe-ecoaula-septiembre-2026.txt';link.click();URL.revokeObjectURL(link.href);showToast('Informe exportado')});
  const report=$('#reportDownload');if(report)report.addEventListener('click',()=>showToast('Informe generado correctamente'));
});

