const renderActiveCourses=()=>{const courses=EcoStore.get('courses',EcoData.courses).filter(course=>course.progress>0).slice(0,3);$('#activeCourses').innerHTML=courses.map(course=>`<article class="active-course"><div class="active-thumb ${course.theme}">${course.icon}</div><div><h3>${course.title}</h3><p>${course.category} · ${Math.ceil(course.lessons*(course.progress/100))} de ${course.lessons} lecciones</p><div class="progress-bar"><i style="width:${course.progress}%"></i></div><span class="course-percent"><span>${course.progress}% completado</span><span>${course.lessons} lecciones</span></span></div><a href="course.html?id=${course.id}" aria-label="Continuar ${course.title}">→</a></article>`).join('')};
const renderCatalog=(filter='all',query='')=>{const courses=EcoStore.get('courses',EcoData.courses).filter(course=>(filter==='all'||course.category===filter)&&(`${course.title} ${course.category} ${course.description}`.toLowerCase().includes(query.toLowerCase())));$('#courseCatalog').innerHTML=courses.map(course=>`<article class="course-card"><div class="course-cover ${course.theme}"><span class="course-tag">${course.category}</span><span class="cover-icon">${course.icon}</span></div><div class="course-body"><div class="course-meta"><span>${course.modules} módulos</span><span>${course.rating} ★</span></div><h3>${course.title}</h3><p>${course.description}</p><a href="course.html?id=${course.id}">${course.progress?'Continuar curso':'Inscribirme'} <span>→</span></a></div></article>`).join('')||'<p>No encontramos cursos con esa búsqueda.</p>'};
document.addEventListener('DOMContentLoaded',()=>{
  renderActiveCourses();renderCatalog();
  $$('.filter-pills button').forEach(button=>button.addEventListener('click',()=>{$$('.filter-pills button').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderCatalog(button.dataset.filter,$('#globalSearch').value)}));
  $('#globalSearch').addEventListener('input',event=>renderCatalog($('.filter-pills .active').dataset.filter,event.target.value));
  $('#joinChallenge').addEventListener('click',event=>{event.target.textContent='✓ Reto aceptado';event.target.disabled=true;showToast('¡Te uniste al reto 7 días sin plástico!')});
  $('.notification-button').addEventListener('click',()=>$('#notificationModal').classList.add('open'));
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('#globalSearch').focus()}});
});

